### ISSUE TITLE
Add emoji for some features in `README.md`

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/larajournal#348]
<img width="819" alt="image" src="https://github.com/user-attachments/assets/b3a4a17a-8dd7-421f-8615-4bf6e6946b23">

**Comment by ypoleto** [comment]
Can I contribute?

**Comment by gomzyakov** [comment]
> Can I contribute?

@ypoleto 

Yes, of course) You can choose suitable emojis (at your discretion) and make a PR.
